[13/Oct/2015 13:51:51] ERROR [django.request:231] Internal Server Error: /rest/get_next_wizard_stage/
Traceback (most recent call last):
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps/web_copo/wizard_views.py", line 56, in get_next_wizard_stage
    da().add_assay_data_to_datafile(study_id, ena_collection_id, datafile_id, attrib)
  File "/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal/ena_da.py", line 498, in add_assay_data_to_datafile
    {'$push': {"studies.studyCOPOMetadata.dataFiles.attributes": assay_data}}
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/collection.py", line 1438, in aggregate
    result = self._command(sock_info, cmd, slave_ok)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/collection.py", line 191, in _command
    allowable_errors)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/pool.py", line 184, in command
    codec_options, check, allowable_errors)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/network.py", line 54, in command
    helpers._check_command_response(response_doc, msg, allowable_errors)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/helpers.py", line 188, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: command SON([('aggregate', 'EnaCollections'), ('pipeline', [{'$match': {'_id': ObjectId('5616734591aaa91fc57df44c')}}, {'$unwind': '$studies'}, {'$match': {'studies.studyCOPOMetadata.id': 'c211ddf80e5a41b59124e7bcad135121'}}, {'$unwind': '$studies.studyCOPOMetadata.dataFiles'}, {'$match': {'studies.studyCOPOMetadata.dataFiles.id': 'bbf43db6c9934203845153d551c44234'}}, {'$push': {'studies.studyCOPOMetadata.dataFiles.attributes': {'question': 'studies.study.assays.assaysTable.genomeSeq.libraryConstruction.libraryStrategy', 'answer': 'AMPLICON'}}}]), ('cursor', {})]) on namespace copo_mongo.$cmd failed: exception: Unrecognized pipeline stage name: '$push'
[13/Oct/2015 14:00:03] DEBUG [web_copo.views:21] ['/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python34.zip', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/api', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo/settings', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[13/Oct/2015 14:00:03] INFO [rdflib:81] RDFLib Version: 4.2.1
[13/Oct/2015 14:00:03] DEBUG [web.apps.web_copo.views:21] ['/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python34.zip', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/api', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo/settings', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[13/Oct/2015 14:00:18] ERROR [django.request:231] Internal Server Error: /rest/get_next_wizard_stage/
Traceback (most recent call last):
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps/web_copo/wizard_views.py", line 56, in get_next_wizard_stage
    da().add_assay_data_to_datafile(study_id, ena_collection_id, datafile_id, attrib)
  File "/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal/ena_da.py", line 505, in add_assay_data_to_datafile
    {"$push": {"studies.studyCOPOMetadata.dataFiles": assay_data}}
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/collection.py", line 1958, in update
    check_keys, multi, manipulate, write_concern)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/collection.py", line 535, in _update
    _check_write_command_response(results)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/helpers.py", line 261, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: cannot use the part (studies of studies.studyCOPOMetadata.dataFiles) to traverse the element ({studies: [ { study: { studyDescription: "", studyFileName: "", studyPublicReleaseDate: "", studyFactors: [ { studyFactorName: "", studyFactorTypeTermSourceREF: "", studyFactorTypeTermAccessionNumber: "", studyFactorType: "" } ], studyPublications: [ { studyPubMedID: "", studyPublicationDOI: "", studyPublicationStatusTermSourceREF: "", studyPublicationStatus: "", studyPublicationAuthorList: "", studyPublicationTitle: "", studyPublicationStatusTermAccessionNumber: "" } ], studySamples: [ [ { name: "", value: "", type: "" }, { items: [ { categoryTerm: "", termAccessionNumber: "", characteristics: "", termSourceREF: "" } ], type: "" } ] ], studyIdentifier: "", studyTitle: "", studyDesignDescriptors: [ { studyDesignTypeTermAccessionNumber: "", studyDesignType: "", studyDesignTypeTermSourceREF: "" } ], studyContacts: [ { studyPersonLastName: "", commentStudyPersonREF: "", studyPersonAffiliation: "", studyPersonEmail: "", studyPersonAddress: "", studyPersonFirstName: "", studyPersonRoles: "", studyPersonFax: "", studyPersonMidInitials: "", studyPersonPhone: "", studyPersonRolesTermSourceREF: "", studyPersonRolesTermAccessionNumber: "" } ], commentStudyFundingAgency: "", studyProtocols: [ { studyProtocolTypeTermSourceREF: "", studyProtocolURI: "", studyProtocolName: "", studyProtocolComponentsTypeTermSourceREF: "", studyProtocolComponentsName: "", studyProtocolParametersNameTermAccessionNumber: "", studyProtocolType: "", studyProtocolParametersName: "", studyProtocolComponentsTypeTermAccessionNumber: "", studyProtocolTypeTermAccessionNumber: "", studyProtocolParametersNameTermSourceREF: "", studyProtocolVersion: "", studyProtocolComponentsType: "", studyProtocolDescription: "" } ], assays: [ { studyAssayTechnologyTypeTermAccessionNumber: "", studyAssayTechnologyType: "", studyAssayMeasurementTypeTermAccessionNumber: "", assaysTable: [ [ { name: "", value: "", type: "" }, { items: [ { parameterTerm: "", termAccessionNumber: "", termSourceREF: "", parameterValue: "" } ], type: "" }, { commentTerm: "", value: "", type: "", name: "" } ] ], studyAssayTechnologyPlatform: "", studyAssayTechnologyTypeTermSourceREF: "", studyAssayMeasurementTypeTermSourceREF: "", studyAssayMeasurementType: "", studyAssayFileName: "" } ], commentStudyGrantNumber: "", studySubmissionDate: "" }, studyCOPOMetadata: { id: "", dataFiles: [ { id: "", fileId: "", attributes: [], deleted: "1", samples: [] } ], studyType: "", deleted: "1", studyReference: "", samples: [ { id: "", deleted: "1" } ] } }, { study: { studyDescription: "", studyFileName: "", studyPublicReleaseDate: "", studyFactors: [ { studyFactorName: "", studyFactorTypeTermSourceREF: "", studyFactorTypeTermAccessionNumber: "", studyFactorType: "" } ], studyPublications: [ { studyPubMedID: "", studyPublicationDOI: "", studyPublicationStatusTermSourceREF: "", studyPublicationStatus: "", studyPublicationAuthorList: "", studyPublicationTitle: "", studyPublicationStatusTermAccessionNumber: "" } ], studySamples: [ [ { name: "", value: "", type: "" }, { items: [ { categoryTerm: "", termAccessionNumber: "", characteristics: "", termSourceREF: "" } ], type: "" } ] ], studyIdentifier: "", studyTitle: "", studyDesignDescriptors: [ { studyDesignTypeTermAccessionNumber: "", studyDesignType: "", studyDesignTypeTermSourceREF: "" } ], studyContacts: [ { studyPersonLastName: "", commentStudyPersonREF: "", studyPersonAffiliation: "", studyPersonEmail: "", studyPersonAddress: "", studyPersonFirstName: "", studyPersonRoles: "", studyPersonFax: "", studyPersonMidInitials: "", studyPersonPhone: "", studyPersonRolesTermSourceREF: "", studyPersonRolesTermAccessionNumber: "" } ], commentStudyFundingAgency: "", studyProtocols: [ { studyProtocolTypeTermSourceREF: "", studyProtocolURI: "", studyProtocolName: "", studyProtocolComponentsTypeTermSourceREF: "", studyProtocolComponentsName: "", studyProtocolParametersNameTermAccessionNumber: "", studyProtocolType: "", studyProtocolParametersName: "", studyProtocolComponentsTypeTermAccessionNumber: "", studyProtocolTypeTermAccessionNumber: "", studyProtocolParametersNameTermSourceREF: "", studyProtocolVersion: "", studyProtocolComponentsType: "", studyProtocolDescription: "" } ], assays: [ { studyAssayTechnologyTypeTermAccessionNumber: "", studyAssayTechnologyType: "", studyAssayMeasurementTypeTermAccessionNumber: "", assaysTable: [ [ { name: "", value: "", type: "" }, { items: [ { parameterTerm: "", termAccessionNumber: "", termSourceREF: "", parameterValue: "" } ], type: "" }, { commentTerm: "", value: "", type: "", name: "" } ] ], studyAssayTechnologyPlatform: "", studyAssayTechnologyTypeTermSourceREF: "", studyAssayMeasurementTypeTermSourceREF: "", studyAssayMeasurementType: "", studyAssayFileName: "" } ], commentStudyGrantNumber: "", studySubmissionDate: "" }, studyCOPOMetadata: { id: "c211ddf80e5a41b59124e7bcad135121", dataFiles: [ { id: "", fileId: "", attributes: [], deleted: "1", samples: [] }, { id: "bbf43db6c9934203845153d551c44234", samples: [], deleted: "0", fileId: "150", attributes: [] }, { id: "a821a0e6d5b945e3bf4b1d81202e6575", samples: [], deleted: "0", fileId: "151", attributes: [] } ], studyType: "genomeSeq", deleted: "0", studyReference: "Genome Seq", samples: [ { id: "", deleted: "1" }, { id: "ae89267c6ea34911a5a10e0c097dd56b", deleted: "0" } ] } } ]})
[13/Oct/2015 14:08:45] DEBUG [web_copo.views:21] ['/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python34.zip', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/api', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo/settings', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[13/Oct/2015 14:08:45] INFO [rdflib:81] RDFLib Version: 4.2.1
[13/Oct/2015 14:08:45] DEBUG [web.apps.web_copo.views:21] ['/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python34.zip', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/api', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo/settings', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[13/Oct/2015 14:13:11] DEBUG [web_copo.views:21] ['/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python34.zip', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/api', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo/settings', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[13/Oct/2015 14:13:11] INFO [rdflib:81] RDFLib Version: 4.2.1
[13/Oct/2015 14:13:12] DEBUG [web.apps.web_copo.views:21] ['/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python34.zip', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/api', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo/settings', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[13/Oct/2015 14:14:39] DEBUG [web_copo.views:21] ['/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python34.zip', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/api', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo/settings', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[13/Oct/2015 14:14:39] INFO [rdflib:81] RDFLib Version: 4.2.1
[13/Oct/2015 14:14:39] DEBUG [web.apps.web_copo.views:21] ['/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python34.zip', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/api', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo/settings', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[13/Oct/2015 14:17:03] DEBUG [web_copo.views:21] ['/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python34.zip', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/api', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo/settings', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[13/Oct/2015 14:17:03] INFO [rdflib:81] RDFLib Version: 4.2.1
[13/Oct/2015 14:17:03] DEBUG [web.apps.web_copo.views:21] ['/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python34.zip', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/api', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo/settings', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[13/Oct/2015 15:09:08] DEBUG [web_copo.views:21] ['/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python34.zip', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/api', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo/settings', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[13/Oct/2015 15:09:09] INFO [rdflib:81] RDFLib Version: 4.2.1
[13/Oct/2015 15:09:09] DEBUG [web.apps.web_copo.views:21] ['/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python34.zip', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/api', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo/settings', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[13/Oct/2015 15:15:59] ERROR [django.request:231] Internal Server Error: /rest/get_next_wizard_stage/
Traceback (most recent call last):
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps/web_copo/wizard_views.py", line 56, in get_next_wizard_stage
    da().add_assay_data_to_datafile(study_id, ena_collection_id, datafile_id, attrib)
  File "/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal/ena_da.py", line 494, in add_assay_data_to_datafile
    {"$push": {"studies.$.studyCOPOMetadata.dataFiles.attributes": assay_data}}
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/collection.py", line 1958, in update
    check_keys, multi, manipulate, write_concern)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/collection.py", line 535, in _update
    _check_write_command_response(results)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/helpers.py", line 261, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: cannot use the part (dataFiles of studies.1.studyCOPOMetadata.dataFiles.attributes) to traverse the element ({dataFiles: [ { id: "", fileId: "", attributes: [], deleted: "1", samples: [] }, { id: "bbf43db6c9934203845153d551c44234", samples: [], deleted: "0", fileId: "150", attributes: [] }, { id: "a821a0e6d5b945e3bf4b1d81202e6575", samples: [], deleted: "0", fileId: "151", attributes: [] } ]})
[13/Oct/2015 15:16:01] ERROR [django.request:231] Internal Server Error: /rest/get_next_wizard_stage/
Traceback (most recent call last):
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps/web_copo/wizard_views.py", line 56, in get_next_wizard_stage
    da().add_assay_data_to_datafile(study_id, ena_collection_id, datafile_id, attrib)
  File "/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal/ena_da.py", line 494, in add_assay_data_to_datafile
    {"$push": {"studies.$.studyCOPOMetadata.dataFiles.attributes": assay_data}}
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/collection.py", line 1958, in update
    check_keys, multi, manipulate, write_concern)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/collection.py", line 535, in _update
    _check_write_command_response(results)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/helpers.py", line 261, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: cannot use the part (dataFiles of studies.1.studyCOPOMetadata.dataFiles.attributes) to traverse the element ({dataFiles: [ { id: "", fileId: "", attributes: [], deleted: "1", samples: [] }, { id: "bbf43db6c9934203845153d551c44234", samples: [], deleted: "0", fileId: "150", attributes: [] }, { id: "a821a0e6d5b945e3bf4b1d81202e6575", samples: [], deleted: "0", fileId: "151", attributes: [] } ]})
[13/Oct/2015 15:16:02] ERROR [django.request:231] Internal Server Error: /rest/get_next_wizard_stage/
Traceback (most recent call last):
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps/web_copo/wizard_views.py", line 56, in get_next_wizard_stage
    da().add_assay_data_to_datafile(study_id, ena_collection_id, datafile_id, attrib)
  File "/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal/ena_da.py", line 494, in add_assay_data_to_datafile
    {"$push": {"studies.$.studyCOPOMetadata.dataFiles.attributes": assay_data}}
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/collection.py", line 1958, in update
    check_keys, multi, manipulate, write_concern)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/collection.py", line 535, in _update
    _check_write_command_response(results)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/helpers.py", line 261, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: cannot use the part (dataFiles of studies.1.studyCOPOMetadata.dataFiles.attributes) to traverse the element ({dataFiles: [ { id: "", fileId: "", attributes: [], deleted: "1", samples: [] }, { id: "bbf43db6c9934203845153d551c44234", samples: [], deleted: "0", fileId: "150", attributes: [] }, { id: "a821a0e6d5b945e3bf4b1d81202e6575", samples: [], deleted: "0", fileId: "151", attributes: [] } ]})
[13/Oct/2015 15:16:02] ERROR [django.request:231] Internal Server Error: /rest/get_next_wizard_stage/
Traceback (most recent call last):
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps/web_copo/wizard_views.py", line 56, in get_next_wizard_stage
    da().add_assay_data_to_datafile(study_id, ena_collection_id, datafile_id, attrib)
  File "/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal/ena_da.py", line 494, in add_assay_data_to_datafile
    {"$push": {"studies.$.studyCOPOMetadata.dataFiles.attributes": assay_data}}
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/collection.py", line 1958, in update
    check_keys, multi, manipulate, write_concern)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/collection.py", line 535, in _update
    _check_write_command_response(results)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/helpers.py", line 261, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: cannot use the part (dataFiles of studies.1.studyCOPOMetadata.dataFiles.attributes) to traverse the element ({dataFiles: [ { id: "", fileId: "", attributes: [], deleted: "1", samples: [] }, { id: "bbf43db6c9934203845153d551c44234", samples: [], deleted: "0", fileId: "150", attributes: [] }, { id: "a821a0e6d5b945e3bf4b1d81202e6575", samples: [], deleted: "0", fileId: "151", attributes: [] } ]})
[13/Oct/2015 15:18:19] ERROR [django.request:231] Internal Server Error: /rest/get_next_wizard_stage/
Traceback (most recent call last):
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps/web_copo/wizard_views.py", line 56, in get_next_wizard_stage
    da().add_assay_data_to_datafile(study_id, ena_collection_id, datafile_id, attrib)
  File "/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal/ena_da.py", line 494, in add_assay_data_to_datafile
    {"$push": {"studies.$.studyCOPOMetadata.dataFiles.attributes": assay_data}}
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/collection.py", line 1958, in update
    check_keys, multi, manipulate, write_concern)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/collection.py", line 535, in _update
    _check_write_command_response(results)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/helpers.py", line 261, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: cannot use the part (dataFiles of studies.1.studyCOPOMetadata.dataFiles.attributes) to traverse the element ({dataFiles: [ { id: "", fileId: "", attributes: [], deleted: "1", samples: [] }, { id: "bbf43db6c9934203845153d551c44234", samples: [], deleted: "0", fileId: "150", attributes: [] }, { id: "a821a0e6d5b945e3bf4b1d81202e6575", samples: [], deleted: "0", fileId: "151", attributes: [] } ]})
[13/Oct/2015 15:18:30] ERROR [django.request:231] Internal Server Error: /rest/get_next_wizard_stage/
Traceback (most recent call last):
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps/web_copo/wizard_views.py", line 56, in get_next_wizard_stage
    da().add_assay_data_to_datafile(study_id, ena_collection_id, datafile_id, attrib)
  File "/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal/ena_da.py", line 494, in add_assay_data_to_datafile
    {"$push": {"studies.$.studyCOPOMetadata.dataFiles.attributes": assay_data}}
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/collection.py", line 1958, in update
    check_keys, multi, manipulate, write_concern)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/collection.py", line 535, in _update
    _check_write_command_response(results)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/helpers.py", line 261, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: cannot use the part (dataFiles of studies.1.studyCOPOMetadata.dataFiles.attributes) to traverse the element ({dataFiles: [ { id: "", fileId: "", attributes: [], deleted: "1", samples: [] }, { id: "bbf43db6c9934203845153d551c44234", samples: [], deleted: "0", fileId: "150", attributes: [] }, { id: "a821a0e6d5b945e3bf4b1d81202e6575", samples: [], deleted: "0", fileId: "151", attributes: [] } ]})
[13/Oct/2015 15:19:03] ERROR [django.request:231] Internal Server Error: /rest/get_next_wizard_stage/
Traceback (most recent call last):
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps/web_copo/wizard_views.py", line 56, in get_next_wizard_stage
    da().add_assay_data_to_datafile(study_id, ena_collection_id, datafile_id, attrib)
  File "/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal/ena_da.py", line 494, in add_assay_data_to_datafile
    {"$push": {"studies.$.studyCOPOMetadata.dataFiles.attributes": assay_data}}
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/collection.py", line 1958, in update
    check_keys, multi, manipulate, write_concern)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/collection.py", line 535, in _update
    _check_write_command_response(results)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/helpers.py", line 261, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: cannot use the part (dataFiles of studies.1.studyCOPOMetadata.dataFiles.attributes) to traverse the element ({dataFiles: [ { id: "", fileId: "", attributes: [], deleted: "1", samples: [] }, { id: "bbf43db6c9934203845153d551c44234", samples: [], deleted: "0", fileId: "150", attributes: [] }, { id: "a821a0e6d5b945e3bf4b1d81202e6575", samples: [], deleted: "0", fileId: "151", attributes: [] } ]})
[13/Oct/2015 15:19:26] ERROR [django.request:231] Internal Server Error: /rest/get_next_wizard_stage/
Traceback (most recent call last):
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps/web_copo/wizard_views.py", line 56, in get_next_wizard_stage
    da().add_assay_data_to_datafile(study_id, ena_collection_id, datafile_id, attrib)
  File "/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal/ena_da.py", line 494, in add_assay_data_to_datafile
    {"$push": {"studies.$.studyCOPOMetadata.dataFiles.attributes": assay_data}}
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/collection.py", line 1958, in update
    check_keys, multi, manipulate, write_concern)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/collection.py", line 535, in _update
    _check_write_command_response(results)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/helpers.py", line 261, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: cannot use the part (dataFiles of studies.1.studyCOPOMetadata.dataFiles.attributes) to traverse the element ({dataFiles: [ { id: "", fileId: "", attributes: [], deleted: "1", samples: [] }, { id: "bbf43db6c9934203845153d551c44234", samples: [], deleted: "0", fileId: "150", attributes: [] }, { id: "a821a0e6d5b945e3bf4b1d81202e6575", samples: [], deleted: "0", fileId: "151", attributes: [] } ]})
[13/Oct/2015 15:19:26] ERROR [django.request:231] Internal Server Error: /rest/get_next_wizard_stage/
Traceback (most recent call last):
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps/web_copo/wizard_views.py", line 56, in get_next_wizard_stage
    da().add_assay_data_to_datafile(study_id, ena_collection_id, datafile_id, attrib)
  File "/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal/ena_da.py", line 494, in add_assay_data_to_datafile
    {"$push": {"studies.$.studyCOPOMetadata.dataFiles.attributes": assay_data}}
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/collection.py", line 1958, in update
    check_keys, multi, manipulate, write_concern)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/collection.py", line 535, in _update
    _check_write_command_response(results)
  File "/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages/pymongo/helpers.py", line 261, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: cannot use the part (dataFiles of studies.1.studyCOPOMetadata.dataFiles.attributes) to traverse the element ({dataFiles: [ { id: "", fileId: "", attributes: [], deleted: "1", samples: [] }, { id: "bbf43db6c9934203845153d551c44234", samples: [], deleted: "0", fileId: "150", attributes: [] }, { id: "a821a0e6d5b945e3bf4b1d81202e6575", samples: [], deleted: "0", fileId: "151", attributes: [] } ]})
[13/Oct/2015 15:19:35] DEBUG [web_copo.views:21] ['/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python34.zip', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/api', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo/settings', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[13/Oct/2015 15:19:35] INFO [rdflib:81] RDFLib Version: 4.2.1
[13/Oct/2015 15:19:35] DEBUG [web.apps.web_copo.views:21] ['/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python34.zip', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/api', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo/settings', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[13/Oct/2015 15:20:29] DEBUG [web_copo.views:21] ['/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python34.zip', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/api', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo/settings', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[13/Oct/2015 15:20:29] INFO [rdflib:81] RDFLib Version: 4.2.1
[13/Oct/2015 15:20:29] DEBUG [web.apps.web_copo.views:21] ['/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python34.zip', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/api', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo/settings', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[13/Oct/2015 15:27:55] DEBUG [web_copo.views:21] ['/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python34.zip', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/api', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo/settings', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[13/Oct/2015 15:27:55] INFO [rdflib:81] RDFLib Version: 4.2.1
[13/Oct/2015 15:27:55] DEBUG [web.apps.web_copo.views:21] ['/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python34.zip', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/fshaw/Documents/dev/environments/copo_python3.4/lib/python3.4/site-packages', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/api', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/dal', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/project_copo/settings', '/Users/fshaw/Dropbox/tgac_dev/prototypes/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
