[14/Sep/2015 17:16:41] DEBUG [web_copo.views:21] ['/Users/etuka/Dropbox/Dev/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/setuptools-15.1-py3.4.egg', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo', '/Users/etuka/Dropbox/Dev/COPO', '/Users/etuka/Dropbox/Dev/COPO/dal', '/Users/etuka/Dropbox/Dev/COPO/api', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo/settings', '/Users/etuka/environments/venv3.4/lib/python34.zip', '/Users/etuka/environments/venv3.4/lib/python3.4', '/Users/etuka/environments/venv3.4/lib/python3.4/plat-darwin', '/Users/etuka/environments/venv3.4/lib/python3.4/lib-dynload', '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/etuka/environments/venv3.4/lib/python3.4/site-packages', '/Users/etuka/Dropbox/Dev/COPO', '/Users/etuka/Dropbox/Dev/COPO/api', '/Users/etuka/Dropbox/Dev/COPO/dal', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo/settings', '/Users/etuka/Dropbox/Dev/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[14/Sep/2015 17:16:41] INFO [rdflib:81] RDFLib Version: 4.2.1
[14/Sep/2015 17:17:12] DEBUG [web_copo.views:21] ['/Users/etuka/Dropbox/Dev/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/setuptools-15.1-py3.4.egg', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo', '/Users/etuka/Dropbox/Dev/COPO', '/Users/etuka/Dropbox/Dev/COPO/dal', '/Users/etuka/Dropbox/Dev/COPO/api', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo/settings', '/Users/etuka/environments/venv3.4/lib/python34.zip', '/Users/etuka/environments/venv3.4/lib/python3.4', '/Users/etuka/environments/venv3.4/lib/python3.4/plat-darwin', '/Users/etuka/environments/venv3.4/lib/python3.4/lib-dynload', '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/etuka/environments/venv3.4/lib/python3.4/site-packages', '/Users/etuka/Dropbox/Dev/COPO', '/Users/etuka/Dropbox/Dev/COPO/api', '/Users/etuka/Dropbox/Dev/COPO/dal', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo/settings', '/Users/etuka/Dropbox/Dev/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[14/Sep/2015 17:17:12] INFO [rdflib:81] RDFLib Version: 4.2.1
[14/Sep/2015 17:17:31] DEBUG [web_copo.views:21] ['/Users/etuka/Dropbox/Dev/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/setuptools-15.1-py3.4.egg', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo', '/Users/etuka/Dropbox/Dev/COPO', '/Users/etuka/Dropbox/Dev/COPO/dal', '/Users/etuka/Dropbox/Dev/COPO/api', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo/settings', '/Users/etuka/environments/venv3.4/lib/python34.zip', '/Users/etuka/environments/venv3.4/lib/python3.4', '/Users/etuka/environments/venv3.4/lib/python3.4/plat-darwin', '/Users/etuka/environments/venv3.4/lib/python3.4/lib-dynload', '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/etuka/environments/venv3.4/lib/python3.4/site-packages', '/Users/etuka/Dropbox/Dev/COPO', '/Users/etuka/Dropbox/Dev/COPO/api', '/Users/etuka/Dropbox/Dev/COPO/dal', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo/settings', '/Users/etuka/Dropbox/Dev/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[14/Sep/2015 17:17:31] INFO [rdflib:81] RDFLib Version: 4.2.1
[14/Sep/2015 20:26:24] ERROR [django.request:231] Internal Server Error: /copo/collection/55edacf791ccd60b090af08f/view
Traceback (most recent call last):
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/django/core/urlresolvers.py", line 364, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/django/core/handlers/base.py", line 87, in get_response
    response = middleware_method(request)
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/django/middleware/common.py", line 72, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/django/core/urlresolvers.py", line 619, in is_valid_path
    resolve(path, urlconf)
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/django/core/urlresolvers.py", line 494, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/django/core/urlresolvers.py", line 343, in resolve
    for pattern in self.url_patterns:
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/django/core/urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/django/core/urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/etuka/environments/venv3.4/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/etuka/Dropbox/Dev/COPO/web/project_copo/urls.py", line 4, in <module>
    import web_copo.views as views
  File "/Users/etuka/Dropbox/Dev/COPO/web/apps/web_copo/views.py", line 18, in <module>
    from web.apps.web_copo.repos.aspera import do_aspera_transfer
  File "/Users/etuka/Dropbox/Dev/COPO/web/apps/web_copo/repos/aspera.py", line 10, in <module>
    from dal import ObjectId
  File "/Users/etuka/Dropbox/Dev/COPO/dal/__init__.py", line 11, in <module>
    from ena_da import EnaCollection
  File "/Users/etuka/Dropbox/Dev/COPO/dal/ena_da.py", line 309
    "unit": auto_fields['unit_' + index_part]
         ^
SyntaxError: invalid syntax
[14/Sep/2015 20:26:42] DEBUG [web_copo.views:21] ['/Users/etuka/Dropbox/Dev/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/setuptools-15.1-py3.4.egg', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo', '/Users/etuka/Dropbox/Dev/COPO', '/Users/etuka/Dropbox/Dev/COPO/dal', '/Users/etuka/Dropbox/Dev/COPO/api', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo/settings', '/Users/etuka/environments/venv3.4/lib/python34.zip', '/Users/etuka/environments/venv3.4/lib/python3.4', '/Users/etuka/environments/venv3.4/lib/python3.4/plat-darwin', '/Users/etuka/environments/venv3.4/lib/python3.4/lib-dynload', '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/etuka/environments/venv3.4/lib/python3.4/site-packages', '/Users/etuka/Dropbox/Dev/COPO', '/Users/etuka/Dropbox/Dev/COPO/api', '/Users/etuka/Dropbox/Dev/COPO/dal', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo/settings', '/Users/etuka/Dropbox/Dev/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[14/Sep/2015 20:26:42] INFO [rdflib:81] RDFLib Version: 4.2.1
[14/Sep/2015 20:49:57] DEBUG [web_copo.views:21] ['/Users/etuka/Dropbox/Dev/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/setuptools-15.1-py3.4.egg', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo', '/Users/etuka/Dropbox/Dev/COPO', '/Users/etuka/Dropbox/Dev/COPO/dal', '/Users/etuka/Dropbox/Dev/COPO/api', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo/settings', '/Users/etuka/environments/venv3.4/lib/python34.zip', '/Users/etuka/environments/venv3.4/lib/python3.4', '/Users/etuka/environments/venv3.4/lib/python3.4/plat-darwin', '/Users/etuka/environments/venv3.4/lib/python3.4/lib-dynload', '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/etuka/environments/venv3.4/lib/python3.4/site-packages', '/Users/etuka/Dropbox/Dev/COPO', '/Users/etuka/Dropbox/Dev/COPO/api', '/Users/etuka/Dropbox/Dev/COPO/dal', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo/settings', '/Users/etuka/Dropbox/Dev/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[14/Sep/2015 20:49:57] INFO [rdflib:81] RDFLib Version: 4.2.1
[14/Sep/2015 20:52:24] DEBUG [web_copo.views:21] ['/Users/etuka/Dropbox/Dev/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/setuptools-15.1-py3.4.egg', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo', '/Users/etuka/Dropbox/Dev/COPO', '/Users/etuka/Dropbox/Dev/COPO/dal', '/Users/etuka/Dropbox/Dev/COPO/api', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo/settings', '/Users/etuka/environments/venv3.4/lib/python34.zip', '/Users/etuka/environments/venv3.4/lib/python3.4', '/Users/etuka/environments/venv3.4/lib/python3.4/plat-darwin', '/Users/etuka/environments/venv3.4/lib/python3.4/lib-dynload', '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/etuka/environments/venv3.4/lib/python3.4/site-packages', '/Users/etuka/Dropbox/Dev/COPO', '/Users/etuka/Dropbox/Dev/COPO/api', '/Users/etuka/Dropbox/Dev/COPO/dal', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo/settings', '/Users/etuka/Dropbox/Dev/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[14/Sep/2015 20:52:24] INFO [rdflib:81] RDFLib Version: 4.2.1
[15/Sep/2015 09:03:44] DEBUG [web_copo.views:21] ['/Users/etuka/Dropbox/Dev/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/setuptools-15.1-py3.4.egg', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo', '/Users/etuka/Dropbox/Dev/COPO', '/Users/etuka/Dropbox/Dev/COPO/dal', '/Users/etuka/Dropbox/Dev/COPO/api', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo/settings', '/Users/etuka/environments/venv3.4/lib/python34.zip', '/Users/etuka/environments/venv3.4/lib/python3.4', '/Users/etuka/environments/venv3.4/lib/python3.4/plat-darwin', '/Users/etuka/environments/venv3.4/lib/python3.4/lib-dynload', '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/etuka/environments/venv3.4/lib/python3.4/site-packages', '/Users/etuka/Dropbox/Dev/COPO', '/Users/etuka/Dropbox/Dev/COPO/api', '/Users/etuka/Dropbox/Dev/COPO/dal', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo/settings', '/Users/etuka/Dropbox/Dev/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[15/Sep/2015 09:03:44] INFO [rdflib:81] RDFLib Version: 4.2.1
[15/Sep/2015 09:34:34] ERROR [django.request:231] Internal Server Error: /rest/receive_data_file_chunked/
Traceback (most recent call last):
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/chunked_upload/views.py", line 104, in post
    return self._post(request, *args, **kwargs)
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/chunked_upload/views.py", line 189, in _post
    chunked_upload = self.create_chunked_upload(save=False, **attrs)
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/chunked_upload/views.py", line 145, in create_chunked_upload
    chunked_upload.file.save(name='', content=ContentFile(''), save=save)
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/django/db/models/fields/files.py", line 89, in save
    self.name = self.storage.save(name, content)
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/django/core/files/storage.py", line 51, in save
    name = self._save(name, content)
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/django/core/files/storage.py", line 193, in _save
    os.makedirs(directory)
  File "/Users/etuka/environments/venv3.4/bin/../lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/etuka/environments/venv3.4/bin/../lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/etuka/environments/venv3.4/bin/../lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/etuka/environments/venv3.4/bin/../lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/etuka/environments/venv3.4/bin/../lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/etuka/environments/venv3.4/bin/../lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/fshaw'
[15/Sep/2015 09:41:33] DEBUG [web_copo.views:21] ['/Users/etuka/Dropbox/Dev/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/setuptools-15.1-py3.4.egg', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo', '/Users/etuka/Dropbox/Dev/COPO', '/Users/etuka/Dropbox/Dev/COPO/dal', '/Users/etuka/Dropbox/Dev/COPO/api', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo/settings', '/Users/etuka/environments/venv3.4/lib/python34.zip', '/Users/etuka/environments/venv3.4/lib/python3.4', '/Users/etuka/environments/venv3.4/lib/python3.4/plat-darwin', '/Users/etuka/environments/venv3.4/lib/python3.4/lib-dynload', '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/etuka/environments/venv3.4/lib/python3.4/site-packages', '/Users/etuka/Dropbox/Dev/COPO', '/Users/etuka/Dropbox/Dev/COPO/api', '/Users/etuka/Dropbox/Dev/COPO/dal', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo/settings', '/Users/etuka/Dropbox/Dev/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[15/Sep/2015 09:41:33] INFO [rdflib:81] RDFLib Version: 4.2.1
[15/Sep/2015 09:41:34] ERROR [django.request:231] Internal Server Error: /rest/receive_data_file/
Traceback (most recent call last):
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/etuka/Dropbox/Dev/COPO/web/apps/web_copo/rest/EnaRest.py", line 224, in receive_data_file
    chunked_upload.file.save(name='', content=ContentFile(''), save=True)
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/django/db/models/fields/files.py", line 89, in save
    self.name = self.storage.save(name, content)
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/django/core/files/storage.py", line 51, in save
    name = self._save(name, content)
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/django/core/files/storage.py", line 193, in _save
    os.makedirs(directory)
  File "/Users/etuka/environments/venv3.4/bin/../lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/etuka/environments/venv3.4/bin/../lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/etuka/environments/venv3.4/bin/../lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/etuka/environments/venv3.4/bin/../lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/etuka/environments/venv3.4/bin/../lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/etuka/environments/venv3.4/bin/../lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/fshaw'
[15/Sep/2015 10:13:45] DEBUG [web_copo.views:21] ['/Users/etuka/Dropbox/Dev/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/setuptools-15.1-py3.4.egg', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo', '/Users/etuka/Dropbox/Dev/COPO', '/Users/etuka/Dropbox/Dev/COPO/dal', '/Users/etuka/Dropbox/Dev/COPO/api', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo/settings', '/Users/etuka/environments/venv3.4/lib/python34.zip', '/Users/etuka/environments/venv3.4/lib/python3.4', '/Users/etuka/environments/venv3.4/lib/python3.4/plat-darwin', '/Users/etuka/environments/venv3.4/lib/python3.4/lib-dynload', '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/etuka/environments/venv3.4/lib/python3.4/site-packages', '/Users/etuka/Dropbox/Dev/COPO', '/Users/etuka/Dropbox/Dev/COPO/api', '/Users/etuka/Dropbox/Dev/COPO/dal', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo/settings', '/Users/etuka/Dropbox/Dev/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[15/Sep/2015 10:13:45] INFO [rdflib:81] RDFLib Version: 4.2.1
[15/Sep/2015 10:17:01] ERROR [django.request:231] Internal Server Error: /rest/inspect_file/
Traceback (most recent call last):
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/etuka/Dropbox/Dev/COPO/web/apps/web_copo/rest/EnaRest.py", line 285, in inspect_file
    if (u.is_fastq_file(file_name)):
  File "/Users/etuka/Dropbox/Dev/COPO/web/apps/web_copo/utils/EnaUtils.py", line 39, in is_fastq_file
    li = f.readline().strip()
  File "/Users/etuka/environments/venv3.4/bin/../lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
[15/Sep/2015 10:19:52] ERROR [django.request:231] Internal Server Error: /rest/inspect_file/
Traceback (most recent call last):
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/etuka/Dropbox/Dev/COPO/web/apps/web_copo/rest/EnaRest.py", line 285, in inspect_file
    if (u.is_fastq_file(file_name)):
  File "/Users/etuka/Dropbox/Dev/COPO/web/apps/web_copo/utils/EnaUtils.py", line 39, in is_fastq_file
    li = f.readline().strip()
  File "/Users/etuka/environments/venv3.4/bin/../lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
[15/Sep/2015 10:23:30] ERROR [django.request:231] Internal Server Error: /rest/inspect_file/
Traceback (most recent call last):
  File "/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/etuka/Dropbox/Dev/COPO/web/apps/web_copo/rest/EnaRest.py", line 285, in inspect_file
    if (u.is_fastq_file(file_name)):
  File "/Users/etuka/Dropbox/Dev/COPO/web/apps/web_copo/utils/EnaUtils.py", line 39, in is_fastq_file
    li = f.readline().strip()
  File "/Users/etuka/environments/venv3.4/bin/../lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
[15/Sep/2015 10:34:48] DEBUG [web_copo.views:21] ['/Users/etuka/Dropbox/Dev/COPO/web', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/etuka/environments/venv3.4/lib/python3.4/site-packages/setuptools-15.1-py3.4.egg', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo', '/Users/etuka/Dropbox/Dev/COPO', '/Users/etuka/Dropbox/Dev/COPO/dal', '/Users/etuka/Dropbox/Dev/COPO/api', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo/settings', '/Users/etuka/environments/venv3.4/lib/python34.zip', '/Users/etuka/environments/venv3.4/lib/python3.4', '/Users/etuka/environments/venv3.4/lib/python3.4/plat-darwin', '/Users/etuka/environments/venv3.4/lib/python3.4/lib-dynload', '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Users/etuka/environments/venv3.4/lib/python3.4/site-packages', '/Users/etuka/Dropbox/Dev/COPO', '/Users/etuka/Dropbox/Dev/COPO/api', '/Users/etuka/Dropbox/Dev/COPO/dal', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo', '/Users/etuka/Dropbox/Dev/COPO/web/project_copo/settings', '/Users/etuka/Dropbox/Dev/COPO/web/apps', '/var/www/copo_www/COPO/', '/var/www/copo_www/COPO/api', '/var/www/copo_www/COPO/dal', '/var/www/copo_www/COPO/web/project_copo', '/var/www/copo_www/COPO/web/project_copo/settings', '/var/www/copo_www/COPO/web/apps']
[15/Sep/2015 10:34:48] INFO [rdflib:81] RDFLib Version: 4.2.1
